### PR TITLE
Issue: #12

### PR DESCRIPTION
**Pull request by SinghArsh04**
User Profile Creation

### CODE REVIEW

**Comment by PrinkalDhingra** [comment]
@SinghArsh04 kindly follow the pr template provided and generate a new pull request.

**Comment by SinghArsh04** [comment]
@PrinkalDhingra where do i get pr template?

**Comment by PrinkalDhingra** [comment]
Issue:#issue number

Short description

**Comment by PrinkalDhingra** [comment]
Follow the above pr template and resolve the conflicts

**Pull request closed without merging**
